DROP TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA;
DROP SEQUENCE GESTAO_RECURSOS_FINANCEIROS.NUMERO_OPERACAO_SEQ;
DELETE FROM GESTAO_RECURSOS_FINANCEIROS."flyway_schema_history" WHERE "version" LIKE '001_017';
