DROP TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA;
DROP TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_ENDERECO;

DELETE FROM GESTAO_RECURSOS_FINANCEIROS."flyway_schema_history" WHERE "version" LIKE '001_001';
