spring:
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:oracle:thin:@//dboracledesenv.poupex.com.br:1521/desenv
    username: USER_GESTAO_RECURSOS_FINANCEIROS
    password: 2mGktD3ep$w3GDdgG
#    url: jdbc:oracle:thin:@//localhost:1521/oracle
#    username: system
#    password: system
  jpa:
    properties:
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    user: GESTAO_RECURSOS_FINANCEIROS
    password: X!aX0Z32QU1#fEg
    ignore-migration-patterns: '*:missing'
    locations:
      - classpath:db/migration
      - classpath:db/callbacks
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://devsso.poupex.com.br/f5-oauth2/v1
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.cache: info
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    org.springframework.amqp: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: debug
poupex:
  api:
    time-out: 3
    terceiros:
      gestao-instrumentos-api-url: https://mocki.io
      auth:
        url: https://hmlsso.poupex.com.br/f5-oauth2/v1/token
        client: d974a758f623c0fb97af568a0a210094a15bdef885b01063
        secret: f14fe88814bf4169fe00beb2e4ab9eddf461e0b488a40094a15bdef885b01063
      endereco-cep:
        url: http://enderecoapihml.hml.cloud.poupex/cep
  minio:
    endpoint: https://miniostage.poupex.com.br
    bucket: gestao-recursos-financeiros-hml
    accessKey: user-gestao-recursos-financeiros-hml
    secretKey: fYbMnnEtgehPNZhR
barramento:
  url: http://homologaesb.poupex.com.br
