CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA
(
    ID          VARCHAR2(64)    NOT NULL,
    NOME        VARCHAR2(128)   NOT NULL,
    ABREVIACAO  VARCHAR2(64)    NOT NULL,
    CADASTRO    TIMESTAMP       NOT NULL,
    ATUALIZACAO TIMESTAMP       NOT NULL,
    CONSTRAINT INSTITUICAO_FINANCEIRA_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT INSTITUICAO_FINANCEIRA_UNIQUE UNIQUE (NOME, ABREVIACAO)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;

CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_ENDERECO
(
    ID                      VARCHAR2(64)    NOT NULL,
    INSTITUICAO_FINANCEIRA  VARCHAR2(64)    NOT NULL,
    CEP                     VARCHAR2(64)    NOT NULL,
    LOGRADOURO              VARCHAR2(64)    NOT NULL,
    NUMERO                  VARCHAR2(64)    NOT NULL,
    COMPLEMENTO             VARCHAR2(64)    NOT NULL,
    CIDADE                  VARCHAR2(64)    NOT NULL,
    UF                      VARCHAR2(64)    NOT NULL,
    CADASTRO                TIMESTAMP       NOT NULL,
    ATUALIZACAO             TIMESTAMP       NOT NULL,
    CONSTRAINT INSTITUICAO_FINANCEIRA_ENDERECO_PK PRIMARY KEY (ID) ENABLE
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
