SELECT * FROM GESTAO_RECURSOS_FINANCEIROS."flyway_schema_history" ORDER BY GESTAO_RECURSOS_FINANCEIROS."flyway_schema_history"."installed_on";

-- ERASE
-- DROP TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO_ARQUIVO;
-- DROP TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO;
-- DROP TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTABIL;
-- DROP TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO;
-- DROP TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_ENDERECO;
-- DROP TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA;
-- DELETE FROM GESTAO_RECURSOS_FINANCEIROS."flyway_schema_history";

--CLEAN
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO_ARQUIVO;
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO;
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTABIL;
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO;
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_ENDERECO;
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA;
