SELECT * FROM GESTAO_RECURSOS_FINANCEIROS."flyway_schema_history" ORDER BY GESTAO_RECURSOS_FINANCEIROS."flyway_schema_history"."installed_on";

-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO;
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTABIL;
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO;
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_ENDERECO;
-- TRUNCATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA;
