-- CREATE OPERACAO_RENDA_FIXA_DEFINITIVA --
CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA
(
    ID                                  VARCHAR2(36)        NOT NULL,
    CADASTRO                            TIMESTAMP           NOT NULL,
    ATUALIZACAO                         TIMESTAMP           NOT NULL,
    NUMERO_OPERACAO                     NUMBER              NOT NULL,
    INSTITUICAO_GIF_CODIGO              NUMBER              NOT NULL,
    OPERACAO_GIF_CODIGO                 NUMBER              NOT NULL,
    TIPO_MERCADO                        VARCHAR2(20)        NOT NULL,
    INSTRUMENTO_FINANCEIRO              VARCHAR2(36)        NOT NULL,
    CODIGO_IF_GRF                       VARCHAR2(30)        NOT NULL,
    CODIGO_CUSTODIA_BB                  VARCHAR2(30)        NOT NULL,
    FORMA_MENSURACAO                    VARCHAR(60)         NOT NULL,
    DATA_EMISSAO                        TIMESTAMP           NOT NULL,
    DATA_LIQUIDACAO                     TIMESTAMP           NOT NULL,
    PRAZO_DC                            INTEGER             NOT NULL,
    PRAZO_DU                            INTEGER             NOT NULL,
    DATA_VENCIMENTO                     TIMESTAMP           NOT NULL,
    EMISSOR                             VARCHAR2(36)        NOT NULL,
    CONTRAPARTE                         VARCHAR2(36)        NOT NULL,
    TIPO_TAXA                           VARCHAR(10)         NOT NULL,
    TAXA                                DECIMAL(10,2)       NULL,
    TAXA_EFETIVA                        DECIMAL(10,2)       NULL,
    INDICE                              VARCHAR2(36)        NULL,
    INDICE_EMISSAO                      VARCHAR2(36)        NULL,
    INDICE_NEGOCIACAO                   VARCHAR2(36)        NULL,
    PERCENTUAL_INDICE                   DECIMAL(10,2)       NULL,
    TAXA_EMISSAO                        DECIMAL(10,2)       NOT NULL,
    TAXA_NEGOCIACAO                     DECIMAL(10,2)       NOT NULL,
    DIAS_UTEIS                          NUMBER(1)           NOT NULL,
    QTD_DIAS                            INTEGER             NOT NULL,
    PU_EMISSAO                          DECIMAL(10,2)       NULL,
    VALOR_FINANCEIRO                    DECIMAL(10,2)       NULL,
    VALOR_RESGATE                       DECIMAL(10,2)       NULL,
    CUPOM                               NUMBER(1)           NOT NULL,
    PERIODO_CUPOM                       VARCHAR(10)         NOT NULL,
    DATA_PRIMEIRO_CUPOM                 TIMESTAMP           NOT NULL,
    OPERADOR_CONTRAPARTE                VARCHAR(100)        NOT NULL,
    VALOR_CORRETAGEM                    DECIMAL(10,2)       NOT NULL,
    PU_ATUAL                            DECIMAL(10,2)       NULL,
    PU_NEGOCIADO                        DECIMAL(10,2)       NULL,
    PU_POUPEX                           DECIMAL(10,2)       NULL,
    PU_CONTRAPARTE                      DECIMAL(10,2)       NULL,
    VALOR_FINANCEIRO_ATUAL              DECIMAL(10,2)       NULL,
    VALOR_FINANCEIRO_NEGOCIADO          DECIMAL(10,2)       NULL,
    VALOR_FINANCEIRO_POUPEX             DECIMAL(10,2)       NULL,
    VALOR_FINANCEIRO_CONTRAPARTE        DECIMAL(10,2)       NULL,
    CONSTRAINT OPERACAO_RENDA_FIXA_DEFINITIVA_PK            PRIMARY KEY (ID) ENABLE,
    CONSTRAINT CHECK_DIAS_UTEIS                             CHECK ( DIAS_UTEIS = 0 OR DIAS_UTEIS = 1 ),
    CONSTRAINT CHECK_CUPOM                                  CHECK ( CUPOM = 0 OR CUPOM = 1),
    CONSTRAINT UNIQUE_NUMERO_OPERACAO                       UNIQUE ( NUMERO_OPERACAO ),
    CONSTRAINT OPERACAO_RENDA_FIXA_DEFINITIVA_EMISSOR_FK_INSTITUICAO_FINANCEIRA FOREIGN KEY (EMISSOR) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA(ID),
    CONSTRAINT OPERACAO_RENDA_FIXA_DEFINITIVA_CONTRAPARTE_FK_INSTITUICAO_FINANCEIRA FOREIGN KEY (CONTRAPARTE) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA(ID),
    CONSTRAINT OPERACAO_RENDA_FIXA_DEFINITIVA_INSTRUMENTO_FINANCEIRO_FK_INSTRUMENTO_FINANCEIRO FOREIGN KEY (INSTRUMENTO_FINANCEIRO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO(ID),
    CONSTRAINT OPERACAO_RENDA_FIXA_DEFINITIVA_INDICE_EMISSAO_FK_INDICADOR_FINANCEIRO FOREIGN KEY (INDICE_EMISSAO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO(ID),
    CONSTRAINT OPERACAO_RENDA_FIXA_DEFINITIVA_INDICE_NEGOCIACAO_FK_INDICADOR_FINANCEIRO FOREIGN KEY (INDICE_NEGOCIACAO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO(ID),
    CONSTRAINT OPERACAO_RENDA_FIXA_DEFINITIVA_INDICE_FK_INDICADOR_FINANCEIRO FOREIGN KEY (INDICE) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO(ID),
    CONSTRAINT CHECK_TAXA CHECK (TIPO_TAXA NOT IN('PRE','PRE_POS') OR (TIPO_TAXA IN('PRE','PRE_POS') AND TAXA IS NOT NULL)),
    CONSTRAINT CHECK_TAXA_EFETIVA CHECK (TIPO_TAXA NOT IN('PRE','PRE_POS') OR (TIPO_TAXA IN('PRE','PRE_POS') AND TAXA_EFETIVA IS NOT NULL)),
    CONSTRAINT CHECK_INDICE CHECK (TIPO_TAXA NOT IN('POS','PRE_POS') OR (TIPO_TAXA IN('POS','PRE_POS') AND INDICE IS NOT NULL)),
    CONSTRAINT CHECK_INDICE_EMISSAO CHECK (TIPO_TAXA NOT IN('POS','PRE_POS') OR (TIPO_TAXA IN('POS','PRE_POS') AND INDICE_EMISSAO IS NOT NULL)),
    CONSTRAINT CHECK_INDICE_NEGOCIACAO CHECK (TIPO_TAXA NOT IN('POS','PRE_POS') OR (TIPO_TAXA IN('POS','PRE_POS') AND INDICE_NEGOCIACAO IS NOT NULL)),
    CONSTRAINT CHECK_PERCENTUAL_INDICE CHECK (TIPO_TAXA NOT IN('POS','PRE_POS') OR (TIPO_TAXA IN('POS','PRE_POS') AND PERCENTUAL_INDICE IS NOT NULL)),
    CONSTRAINT CHECK_PU_EMISSAO CHECK (TIPO_MERCADO != 'MERCADO_PRIMARIO' OR (TIPO_MERCADO = 'MERCADO_PRIMARIO' AND PU_EMISSAO IS NOT NULL)),
    CONSTRAINT CHECK_VALOR_FINANCEIRO CHECK (TIPO_MERCADO != 'MERCADO_PRIMARIO' OR (TIPO_MERCADO = 'MERCADO_PRIMARIO' AND VALOR_FINANCEIRO IS NOT NULL)),
    CONSTRAINT CHECK_VALOR_RESGATE CHECK (TIPO_MERCADO != 'MERCADO_PRIMARIO' OR (TIPO_MERCADO = 'MERCADO_PRIMARIO' AND VALOR_RESGATE IS NOT NULL)),
    CONSTRAINT CHECK_PU_ATUAL CHECK (TIPO_MERCADO != 'MERCADO_SECUNDARIO' OR (TIPO_MERCADO = 'MERCADO_SECUNDARIO' AND PU_ATUAL IS NOT NULL)),
    CONSTRAINT CHECK_PU_NEGOCIADO CHECK (TIPO_MERCADO != 'MERCADO_SECUNDARIO' OR (TIPO_MERCADO = 'MERCADO_SECUNDARIO' AND PU_NEGOCIADO IS NOT NULL)),
    CONSTRAINT CHECK_PU_POUPEX CHECK (TIPO_MERCADO != 'MERCADO_SECUNDARIO' OR (TIPO_MERCADO = 'MERCADO_SECUNDARIO' AND PU_POUPEX IS NOT NULL)),
    CONSTRAINT CHECK_PU_CONTRAPARTE CHECK (TIPO_MERCADO != 'MERCADO_SECUNDARIO' OR (TIPO_MERCADO = 'MERCADO_SECUNDARIO' AND PU_CONTRAPARTE IS NOT NULL)),
    CONSTRAINT CHECK_VALOR_FINANCEIRO_ATUAL CHECK (TIPO_MERCADO != 'MERCADO_SECUNDARIO' OR (TIPO_MERCADO = 'MERCADO_SECUNDARIO' AND VALOR_FINANCEIRO_ATUAL IS NOT NULL)),
    CONSTRAINT CHECK_VALOR_FINANCEIRO_NEGOCIADO CHECK (TIPO_MERCADO != 'MERCADO_SECUNDARIO' OR (TIPO_MERCADO = 'MERCADO_SECUNDARIO' AND VALOR_FINANCEIRO_NEGOCIADO IS NOT NULL)),
    CONSTRAINT CHECK_VALOR_FINANCEIRO_POUPEX CHECK (TIPO_MERCADO != 'MERCADO_SECUNDARIO' OR (TIPO_MERCADO = 'MERCADO_SECUNDARIO' AND VALOR_FINANCEIRO_POUPEX IS NOT NULL)),
    CONSTRAINT CHECK_VALOR_FINANCEIRO_CONTRAPARTE CHECK (TIPO_MERCADO != 'MERCADO_SECUNDARIO' OR (TIPO_MERCADO = 'MERCADO_SECUNDARIO' AND VALOR_FINANCEIRO_CONTRAPARTE IS NOT NULL))
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;

-- COMMENT --
COMMENT
ON TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA
    IS 'Tabela responsável por armazenar os dados das operações financeiras.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.ID
    IS 'Identificador único.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.NUMERO_OPERACAO
    IS 'Número da operação.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.INSTITUICAO_GIF_CODIGO
    IS 'Código do registro da instituição na aplicação Gestão de Instrumentos Financeiros.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.OPERACAO_GIF_CODIGO
    IS 'Código do registro da operação na aplicação Gestão de Instrumentos Financeiros.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.TIPO_MERCADO
    IS 'Tipo do Mercado a qual o instrumento financeiro é enquadrado.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.INSTRUMENTO_FINANCEIRO
    IS 'Instrumento financeiro usado na operação';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.CODIGO_IF_GRF
    IS 'Código de controle interno do GRF para o instrumento financeiro.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.CODIGO_CUSTODIA_BB
    IS 'Código de custódia do Banco do Brasil';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.FORMA_MENSURACAO
    IS 'Forma de mensuração da Operação Renda Fixa Definitiva';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.DATA_EMISSAO
    IS 'Data da Emissão da Operação Renda Fixa Definitiva';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.DATA_LIQUIDACAO
    IS 'Data da liquidação da Operação Renda Fixa Definitiva';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.PRAZO_DC
    IS 'Prazo DC';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.PRAZO_DU
    IS 'Prazo DU';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.DATA_VENCIMENTO
    IS 'Data vencimento';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.EMISSOR
    IS 'Instituição emissora do titulo financeiro';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.CONTRAPARTE
    IS 'Instituição contraparte do titulo financeiro';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.TIPO_TAXA
    IS 'Tipo de taxa';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.TAXA
    IS 'Valor em percentual da taxa, valido para TIPO_TAXA igual a PRE ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.TAXA_EFETIVA
    IS 'Valor em percentual da taxa efetiva, valido para TIPO_TAXA igual a PRE ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.INDICE_EMISSAO
    IS 'Indice emissão (Indicador Financeiro), valido para TIPO_TAXA igual a POS ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.INDICE
    IS 'Indice (Indicador Financeiro), valido para TIPO_TAXA igual a POS ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.INDICE_NEGOCIACAO
    IS 'Indice de negociação (Indicador Financeiro), valido para TIPO_TAXA igual a POS ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.PERCENTUAL_INDICE
    IS 'Valor em percentual do percentual indice, valido para TIPO_TAXA igual a POS ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.TAXA_EMISSAO
    IS 'Valor da taxa de emissão, valido para TIPO_TAXA igual a PRE ou POS ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.TAXA_NEGOCIACAO
    IS 'Valor da taxa de negociação, valido para TIPO_TAXA igual a PRE ou POS ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.DIAS_UTEIS
    IS 'Indicação da forma de contagem do prazo em dias úteis ou dias corridos';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.QTD_DIAS
    IS 'Quantidade de dias';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.PU_EMISSAO
    IS 'Valor PU emissão, valido para TIPO_MERCADO igual a MERCADO_PRIMARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.VALOR_FINANCEIRO
    IS 'Valor financeiro, valido para TIPO_MERCADO igual a MERCADO_PRIMARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.VALOR_RESGATE
    IS 'Valor resgate, valido para TIPO_MERCADO igual a MERCADO_PRIMARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.CUPOM
    IS 'Indica verdadeiro (1) ou falso (0) para o registro do cupom';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.PERIODO_CUPOM
    IS 'Período do cupom';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.DATA_PRIMEIRO_CUPOM
    IS 'Data do primeiro cupom';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.OPERADOR_CONTRAPARTE
    IS 'Operador contratande';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.VALOR_CORRETAGEM
    IS 'Valor da corretagem';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.PU_ATUAL
    IS 'PU atual (curva B3), valido para TIPO_MERCADO igual a MERCADO_SECUNDARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.PU_NEGOCIADO
    IS 'PU negociado, valido para TIPO_MERCADO igual a MERCADO_SECUNDARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.PU_POUPEX
    IS 'PU agio/desagio (POUPEX), valido para TIPO_MERCADO igual a MERCADO_SECUNDARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.PU_CONTRAPARTE
    IS 'PU agio/desagio (contraparte), valido para TIPO_MERCADO igual a MERCADO_SECUNDARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.VALOR_FINANCEIRO_ATUAL
    IS 'Valor financeiro atual (curva B3), valido para TIPO_MERCADO igual a MERCADO_SECUNDARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.VALOR_FINANCEIRO_NEGOCIADO
    IS 'Valor financeiro negociado, valido para TIPO_MERCADO igual a MERCADO_SECUNDARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.VALOR_FINANCEIRO_POUPEX
    IS 'Valor financeiro agio/desagio (POUPEX), valido para TIPO_MERCADO igual a MERCADO_SECUNDARIO';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.VALOR_FINANCEIRO_CONTRAPARTE
    IS 'Valor financeiro agio/desagio (contraparte), valido para TIPO_MERCADO igual a MERCADO_SECUNDARIO';

-- GRANTS --
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA TO USER_GESTAO_RECURSOS_FINANCEIROS;

CREATE SEQUENCE GESTAO_RECURSOS_FINANCEIROS.NUMERO_OPERACAO_SEQ MAXVALUE 9999;

GRANT SELECT ON GESTAO_RECURSOS_FINANCEIROS.NUMERO_OPERACAO_SEQ TO USER_GESTAO_RECURSOS_FINANCEIROS;


