/**
DROP TABLE GESTAO_RECURSOS_FINANCEIROS.AUDITORIA;
*/
CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.AUDITORIA
(
    ID                     VARCHAR2(36)   NOT NULL,
    AUTH_CHAVE             VARCHAR2(128)  NOT NULL,
    AUTH_CLIENTE           VARCHAR2(128)  NOT NULL,
    OPERADOR_IDENTIFICADOR VARCHAR2(128)  NOT NULL,
    OPERADOR_NOME          VARCHAR2(128)  NOT NULL,
    OPERADOR_UNIDADE       VARCHAR2(128)  NOT NULL,
    TIPO                   VARCHAR2(128),
    RECURSO                VARCHAR2(128),
    ENTRADA_PONTO          VARCHAR2(1024) NOT NULL,
    ENTRADA_PARAMETROS     VARCHAR2(2048),
    ENTRADA_OBSERVACOES    VARCHAR2(2048),
    RESULTADOS             CLOB,
    SUCESSO                NUMBER(1)      NOT NULL,
    CADASTRO               TIMESTAMP      NOT NULL,
    ATUALIZACAO            TIMESTAMP      NOT NULL,
    CONSTRAINT AUDITORIA_PK PRIMARY KEY (ID) ENABLE
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.AUDITORIA TO USER_GESTAO_RECURSOS_FINANCEIROS;

COMMENT ON TABLE GESTAO_RECURSOS_FINANCEIROS.AUDITORIA
    IS 'Operações auditadas da api';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.ID
    IS 'Identificador único - Chave primária';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.OPERADOR_IDENTIFICADOR
    IS 'Chave de identificação do operador - CPF ou outra chave única';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.OPERADOR_NOME
    IS 'Nome do operador';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.OPERADOR_UNIDADE
    IS 'Unidade do operador - UTA';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.TIPO
    IS 'Tipo da operação - Dominio AuditoriaTipo (ex: API)';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.ENTRADA_PONTO
    IS 'Referência da execução. Exemplo: método, sp, chamada, etc';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.ENTRADA_PARAMETROS
    IS 'Parametros para a excução da operação';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.ENTRADA_OBSERVACOES
    IS 'Observações da entrada. Anotações, tipos, etc';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.RESULTADOS
    IS 'Resultado da operação';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.CADASTRO
    IS 'Data/Hora do cadastro do dado.';

COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.AUDITORIA.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
