CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO
(
    ID                              VARCHAR2(36)    NOT NULL,
    CADASTRO                        TIMESTAMP       NOT NULL,
    ATUALIZACAO                     TIMESTAMP       NOT NULL,
    SIGLA                           VARCHAR2(64)    NOT NULL,
    NOME                            VARCHAR2(256)   NOT NULL,
    PERIODICIDADE                   VARCHAR2(64)    NOT NULL,
    CONSTRAINT INDICADOR_FINANCEIRO_PK  PRIMARY KEY (ID) ENABLE,
    CONSTRAINT INDICADOR_FINANCEIRO_UNIQUE UNIQUE (SIGLA)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
COMMENT
    ON TABLE GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO
    IS 'Indicadores financeiros.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO.ID
    IS 'Identificador único.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO.SIGLA
    IS 'Sigla do Indicador Financeiro. BACEN.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO.NOME
    IS 'Nome do Indicador Financeiro (descrição).';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO.PERIODICIDADE
    IS 'Periodicidade do Indicador Financeiro (descrição).';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO TO USER_GESTAO_RECURSOS_FINANCEIROS;
