CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.TITULO_PRIVADO
(
    ID                                  VARCHAR2(36)    NOT NULL,
    SIGLA                               VARCHAR2(20)    NOT NULL,
    CONSTRAINT TITULO_PRIVADO_PK PRIMARY KEY (ID) USING INDEX ENABLE,
    CONSTRAINT TITULO_PRIVADO_ID_FK_INSTRUMENTO_FINANCEIRO FOREIGN KEY (ID) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO(ID)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
COMMENT
    ON TABLE GESTAO_RECURSOS_FINANCEIROS.TITULO_PRIVADO
    IS 'Titulos publicos (tabela complementada pela informacao_financeira no GIF)';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.TITULO_PRIVADO.ID
    IS 'Identificador único.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.TITULO_PRIVADO.SIGLA
    IS 'Sigla do Titulo Publico';
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.TITULO_PRIVADO TO USER_GESTAO_RECURSOS_FINANCEIROS;
