
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA RENAME COLUMN INSTRUMENTO_FINANCEIRO_GRF_CODIGO TO CODIGO_IF_GRF;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA MODIFY TAXA DECIMAL(10,2) NULL;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA ADD TAXA_EFETIVA DECIMAL(10,2) NULL;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA ADD INDICE DECIMAL(10,2) NULL;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA ADD PERCENTUAL_INDICE DECIMAL(10,2) NULL;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA ADD CONSTRAINT CHECK_TAXA CHECK (TIPO_TAXA NOT IN('PRE','PRE_POS') OR (TIPO_TAXA IN('PRE','PRE_POS') AND TAXA IS NOT NULL));
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA ADD CONSTRAINT CHECK_TAXA_EFETIVA CHECK (TIPO_TAXA NOT IN('PRE','PRE_POS') OR (TIPO_TAXA IN('PRE','PRE_POS') AND TAXA_EFETIVA IS NOT NULL));
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA ADD CONSTRAINT CHECK_INDICE CHECK (TIPO_TAXA NOT IN('POS','PRE_POS') OR (TIPO_TAXA IN('POS','PRE_POS') AND INDICE IS NOT NULL));
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA ADD CONSTRAINT CHECK_PERCENTUAL_INDICE CHECK (TIPO_TAXA NOT IN('POS','PRE_POS') OR (TIPO_TAXA IN('POS','PRE_POS') AND PERCENTUAL_INDICE IS NOT NULL));

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO RENAME COLUMN INSTRUMENTO_FINANCEIRO_GIF_CODIGO TO CODIGO_GIF;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO RENAME CONSTRAINT UNIQUE_INSTRUMENTO_FINANCEIRO_GIF_CODIGO TO UNIQUE_CODIGO_GIF;
