ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_ENDERECO ADD BAIRRO VARCHAR(30);

COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_ENDERECO.BAIRRO
    IS 'Bairro do endereço.';
