
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_PRIMARIO DROP CONSTRAINT CHECK_DIAS_UTEIS_TAXA_PRE;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_PRIMARIO RENAME COLUMN DIAS_UTEIS_TAXA_PRE TO DIAS_UTEIS_EMISSAO;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_PRIMARIO ADD CONSTRAINT CHECK_DIAS_UTEIS_EMISSAO CHECK (TIPO_TAXA = 'POS' OR (TIPO_TAXA IN('PRE','PRE_POS') AND ( DIAS_UTEIS_EMISSAO IS NOT NULL AND (DIAS_UTEIS_EMISSAO = 0 OR DIAS_UTEIS_EMISSAO = 1 ))));

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_PRIMARIO DROP CONSTRAINT CHECK_DIAS_UTEIS_INDICE;
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_PRIMARIO DROP COLUMN DIAS_UTEIS_INDICE;


ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP CONSTRAINT CHECK_SECUNDARIO_TAXA_PRE;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO RENAME COLUMN DIAS_UTEIS_TAXA_PRE TO DIAS_UTEIS_EMISSAO;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO ADD CONSTRAINT CHECK_SECUN_DIAS_UTEIS_EMISSAO CHECK (TIPO_TAXA = 'POS' OR (TIPO_TAXA IN('PRE','PRE_POS') AND ( DIAS_UTEIS_EMISSAO IS NOT NULL AND (DIAS_UTEIS_EMISSAO = 0 OR DIAS_UTEIS_EMISSAO = 1 ))));

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP CONSTRAINT CHECK_DIAS_UTEIS_TAXA_PRE_NEGOCIACAO;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO RENAME COLUMN DIAS_UTEIS_TAXA_PRE_NEGOCIACAO TO DIAS_UTEIS_NEGOCIACAO;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO ADD CONSTRAINT CHECK_DIAS_UTEIS_NEGOCIACAO CHECK (TIPO_TAXA = 'POS' OR (TIPO_TAXA IN('PRE','PRE_POS') AND ( DIAS_UTEIS_NEGOCIACAO IS NOT NULL AND (DIAS_UTEIS_NEGOCIACAO = 0 OR DIAS_UTEIS_NEGOCIACAO = 1 ))));

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP CONSTRAINT CHECK_SECUNDARIO_DIAS_UTEIS_INDICE;
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP COLUMN DIAS_UTEIS_INDICE;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP CONSTRAINT CHECK_DIAS_UTEIS_INDICE_NEGOCIACAO;
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP COLUMN DIAS_UTEIS_INDICE_NEGOCIACAO;
