CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO
(
    ID                                  VARCHAR2(36)    NOT NULL,
    SIGLA                               VARCHAR2(20)    NOT NULL,
    ISIN                                VARCHAR2(12)    NOT NULL,
    DATA_EMISSAO                        TIMESTAMP       NOT NULL,
    DATA_VENCIMENTO                     TIMESTAMP       NOT NULL,
    CODIGO_SELIC                        NUMBER(12)      NOT NULL,
    CUPOM                               NUMBER(1)       NOT NULL,
    CONSTRAINT TITULO_PUBLICO_PK PRIMARY KEY (ID) USING INDEX ENABLE,
    CONSTRAINT TITULO_PUBLICO_ID_FK_INSTRUMENTO_FINANCEIRO FOREIGN KEY (ID) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO(ID)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
COMMENT
    ON TABLE GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO
    IS 'Titulo publico herda dados de Instrumento Financeiro (tabela complementada pela informacao_financeira no GIF)';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO.ID
    IS 'Identificador único.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO.SIGLA
    IS 'Sigla do Titulo Publico';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO.ISIN
    IS 'Sigla isin';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO.DATA_EMISSAO
    IS 'Data de emissao do titulo';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO.DATA_VENCIMENTO
    IS 'Data de vencimento do titulo';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO.CODIGO_SELIC
    IS 'Codigo da SELIC';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO.CUPOM
    IS 'CUPOME';
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.TITULO_PUBLICO TO USER_GESTAO_RECURSOS_FINANCEIROS;
