ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO ADD RESUMO VARCHAR2(3000);

COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.RESUMO
    IS 'Campo de resumo do risco de classificação. Assiciação só para classificação';
