CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FINANCEIRA
(
    ID                                  VARCHAR2(36)    NOT NULL,
    CADASTRO                            TIMESTAMP       NOT NULL,
    ATUALIZACAO                         TIMESTAMP       NOT NULL,
    INSTITUICAO_GIF_CNPJ                VARCHAR(11)     NOT NULL,
    TIPO_MERCADO                        VARCHAR2(20)    NOT NULL, ---- ENUM
    INSTRUMENTO_FINANCEIRO_GIF_CODIGO   NUMBER(9)       NOT NULL,
    INSTRUMENTO_FINANCEIRO_GRF_CODIGO   VARCHAR2(30)    NOT NULL,
    CODIGO_CUSTODIA_BB                  VARCHAR2(30)    NOT NULL,
    FORMA_MENSURACAO                    VARCHAR(60)     NOT NULL, ---- ENUM JÁ EXISTE
    DATA_ADMISSAO                       TIMESTAMP       NOT NULL,
    DATA_LIQUIDACAO                     TIMESTAMP       NOT NULL,
    PRAZO_DC                            INTEGER         NOT NULL,
    PRAZO_DU                            INTEGER         NOT NULL,
    DATA_VENCIMENTO                     TIMESTAMP       NOT NULL,
    EMISSOR                             VARCHAR2(36)    NOT NULL,
    CONTRAPARTE                         VARCHAR2(36)    NOT NULL,
    TIPO_TAXA                           VARCHAR(10)     NOT NULL, --- ENUM
    TAXA                                DECIMAL(10,2)   NOT NULL,
	DIAS_UTEIS                          CHAR(5) CHECK ( DIAS_UTEIS ) IN ('TRUE', 'FALSE')   NOT NULL,
	QTD_DIAS                            INTEGER         NOT NULL,
	PU_EMISSAO                          DECIMAL(10,2)   NOT NULL,
	VALOR_FINANCEIRO                    DECIMAL(10,2)   NOT NULL,
	VALOR_RESGATE                       DECIMAL(10,2)   NOT NULL,
    CUPOM                               CHAR(5) CHECK ( CUPOM ) IN ('TRUE', 'FALSE')   NOT NULL,
    PERIODO_CUPOM                       VARCHAR(10)     NOT NULL, --- ENUM
    DATA_PRIMEIRO_CUPOM                 TIMESTAMP       NOT NULL,
    OPERADOR_CONTRAPARTE                VARCHAR(100)    NOT NULL,
    VALOR_CORRETAGEM                    DECIMAL(10,2)   NOT NULL,
    CONSTRAINT OPERACAO_FINANCEIRA_PK  PRIMARY KEY (ID) ENABLE,
    CONSTRAINT OPERACAO_FINANCEIRA_EMISSOR_FK_INSTITUICAO_FINANCEIRA FOREIGN KEY (EMISSOR) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA (ID),
    CONSTRAINT OPERACAO_FINANCEIRA_CONTRAPARTE_FK_INSTITUICAO_FINANCEIRA FOREIGN KEY (CONTRAPARTE) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA (ID)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
COMMENT
ON TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FINANCEIRA
    IS 'Tabela responsável por armazenar os dados das operações financeiras.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FINANCEIRA.ID
    IS 'Identificador único.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FINANCEIRA.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FINANCEIRA.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO.INSTITUICAO_GIF_CODIGO
    IS 'Vinculo com a Instituiçao no GIF.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO.INSTRUMENTO_FINANCEIRO_GIF_CODIGO
    IS 'Vinculo com o Instrumento Financeiro no GIF.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO_ARQUIVO.TIPO
    IS 'Tipo do arquivo.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO_ARQUIVO.TAMANHO
    IS 'Tamanho do arquivo no momento do salvamento.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO_ARQUIVO.CAMINHO
    IS 'Caminho/Path do arquivo.';
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO_ARQUIVO TO USER_GESTAO_RECURSOS_FINANCEIROS;
