CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO
(
    ID                          VARCHAR2(36)  NOT NULL,
    TIPO_OPERACAO               VARCHAR2(36)  NOT NULL,
    EMPRESA                     VARCHAR2(36)  NOT NULL,
    EMPRESA_AGENCIA             VARCHAR2(36)  NOT NULL,
    EMPRESA_CONTA               VARCHAR2(36)  NOT NULL,
    FUNDO_INVESTIMENTO          VARCHAR2(36)  NOT NULL,
    DATA                        DATE          NOT NULL,
    DATA_COTIZACAO              DATE          NOT NULL,
    DATA_LIQUIDACAO             DATE          NOT NULL,
    VALOR_FINANCEIRO            NUMBER(30, 8) NOT NULL,
    VALOR_COTA                  NUMBER(30, 8) NOT NULL,
    QUANTIDADE                  NUMBER(30, 8) NOT NULL,
    CUSTOS_VALOR_CORRETAGEM     NUMBER(30, 8) NOT NULL,
    CUSTOS_INDICADOR_FINANCEIRO VARCHAR2(36)  NOT NULL,
    CONTRAPARTE_OPERADOR        VARCHAR2(256) NOT NULL,
    CONSTRAINT OPERACAO_FUNDO_INVESTIMENTO_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT OPERACAO_FUNDO_INVESTIMENTO_FK_OPERACAO FOREIGN KEY (ID) REFERENCES GESTAO_RECURSOS_FINANCEIROS.OPERACAO (ID),
    CONSTRAINT OPERACAO_FUNDO_INVESTIMENTO_FK_FUNDO_INVESTIMENTO FOREIGN KEY (FUNDO_INVESTIMENTO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.FUNDOS_INVESTIMENTOS (ID),
    CONSTRAINT OPERACAO_FUNDO_INVESTIMENTO_FK_INDICADOR_FINANCEIRO FOREIGN KEY (CUSTOS_INDICADOR_FINANCEIRO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO (ID)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO TO USER_GESTAO_RECURSOS_FINANCEIROS;

COMMENT ON TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO
    IS 'Tabela responsável por armazenar os dados das operações financeiras - Fundos Investimento.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.ID
    IS 'Identificador único.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.EMPRESA
    IS 'Empresa da operação (Inicial FHE ou POUPEX, Dominio: Empresa).';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.EMPRESA_AGENCIA
    IS 'Empresa: Agência da empresa.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.EMPRESA_CONTA
    IS 'Empresa: Conta da empresa.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.FUNDO_INVESTIMENTO
    IS 'Fundo de investimento: mapeamento com tabela GESTAO_RECURSOS_FINANCEIROS.FUNDOS_INVESTIMENTOS.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.DATA
    IS 'Data de aplicação.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.DATA_COTIZACAO
    IS 'Data de cotização.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.DATA_LIQUIDACAO
    IS 'Data de liquidação.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.VALOR_FINANCEIRO
    IS 'Valor financeiro.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.VALOR_COTA
    IS 'Valor cota.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.QUANTIDADE
    IS 'Quantidade cota.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.CUSTOS_VALOR_CORRETAGEM
    IS 'Valor da corretagem da operação.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.CUSTOS_INDICADOR_FINANCEIRO
    IS 'Custos: Indicador financeiro atrelado ao custo.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO.CONTRAPARTE_OPERADOR
    IS 'Contraparte: Nome do operador';

CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO
(
    ID                          VARCHAR2(36)   NOT NULL,
    CADASTRO                    TIMESTAMP      NOT NULL,
    ATUALIZACAO                 TIMESTAMP      NOT NULL,
    OPERACAO_FUNDO_INVESTIMENTO VARCHAR(36)    NOT NULL,
    NOME                        VARCHAR2(64)   NOT NULL,
    TIPO                        VARCHAR2(36)   NOT NULL,
    TAMANHO                     NUMBER         NOT NULL,
    CAMINHO                     VARCHAR2(1024) NOT NULL,
    CONSTRAINT OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO_FK_OPERACAO_FUNDO_INVESTIMENTO FOREIGN KEY (OPERACAO_FUNDO_INVESTIMENTO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO (ID)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO TO USER_GESTAO_RECURSOS_FINANCEIROS;

COMMENT ON TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO
    IS 'Tabela responsável por armazenar os dados dos arquivos das operações financeiras - Fundo Investimento.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO.ID
    IS 'Identificador único.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO.OPERACAO_FUNDO_INVESTIMENTO
    IS 'Vinculo com a operação fundo investimento: tabela OPERACAO_FUNDO_INVESTIMENTO.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO.NOME
    IS 'Nome do arquivo.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO.TIPO
    IS 'Tipo do arquivo.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO.TAMANHO
    IS 'Tamanho do arquivo no momento do salvamento.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_FUNDO_INVESTIMENTO_ARQUIVO.CAMINHO
    IS 'Caminho/Path do arquivo.';

CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.FUNDO_INVESTIMENTO_SALDO
(
    ID                 VARCHAR2(36)  NOT NULL,
    CADASTRO           TIMESTAMP     NOT NULL,
    ATUALIZACAO        TIMESTAMP     NOT NULL,
    FUNDO_INVESTIMENTO VARCHAR2(36)  NOT NULL,
    SALDO_FINANCEIRO   NUMBER(30, 8) NOT NULL,
    SALDO_COTA         NUMBER(30, 8) NOT NULL,
    CONSTRAINT FUNDO_INVESTIMENTO_SALDO_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT FUNDO_INVESTIMENTO_SALDO_FK_FUNDO_INVESTIMENTO FOREIGN KEY (FUNDO_INVESTIMENTO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.FUNDOS_INVESTIMENTOS (ID)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.FUNDO_INVESTIMENTO_SALDO TO USER_GESTAO_RECURSOS_FINANCEIROS;

COMMENT ON TABLE GESTAO_RECURSOS_FINANCEIROS.FUNDO_INVESTIMENTO_SALDO
    IS 'Tabela responsável por armazenar os dados saldos das operações - Fundo Investimento.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.FUNDO_INVESTIMENTO_SALDO.ID
    IS 'Identificador único.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.FUNDO_INVESTIMENTO_SALDO.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.FUNDO_INVESTIMENTO_SALDO.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.FUNDO_INVESTIMENTO_SALDO.FUNDO_INVESTIMENTO
    IS 'Vinculo tabela. Tabela: FUNDO_INVESTIMENTO.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.FUNDO_INVESTIMENTO_SALDO.SALDO_FINANCEIRO
    IS 'Saldo financeiro consolidado.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.FUNDO_INVESTIMENTO_SALDO.SALDO_COTA
    IS 'Saldo cota consolidado.';
