CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO
(
    ID                      VARCHAR2(36)    NOT NULL,
    CADASTRO                TIMESTAMP       NOT NULL,
    ATUALIZACAO             TIMESTAMP       NOT NULL,
    INSTITUICAO_FINANCEIRA  VARCHAR2(36)    NOT NULL,
    NOME                    VARCHAR2(256)   NOT NULL,
    EMAIL                   VARCHAR2(256)   ,
    CARGO_SETOR             VARCHAR2(256)   ,
    TELEFONE1               VARCHAR2(40)    ,
    TELEFONE2               VARCHAR2(40)    ,
    CONSTRAINT INSTITUICAO_FINANCEIRA_CONTATO_PK                        PRIMARY KEY (ID) ENABLE,
    CONSTRAINT INSTITUICAO_FINANCEIRA_CONTATO_FK_INSTITUICAO_FINANCEIRA FOREIGN KEY (INSTITUICAO_FINANCEIRA) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA (ID)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
COMMENT
    ON TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO
    IS 'Contatos da Instituição Financeira.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO.ID
    IS 'Identificador único.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO.INSTITUICAO_FINANCEIRA
    IS 'Vinculo da instituição financeira (INSTITUICAO_FINANCEIRA).';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO.NOME
    IS 'Nome do contato.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO.EMAIL
    IS 'Endereço de email do contato.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO.CARGO_SETOR
    IS 'Cargo e/ou setor do contato.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO.TELEFONE1
    IS 'Número do contato (1).';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO.TELEFONE2
    IS 'Número do contato (2).';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_CONTATO TO USER_GESTAO_RECURSOS_FINANCEIROS;
