CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA
(
    ID              VARCHAR2(36)    NOT NULL,
    CADASTRO        TIMESTAMP       NOT NULL,
    ATUALIZACAO     TIMESTAMP       NOT NULL,
    EMPRESA         VARCHAR(36)     NOT NULL,
    CONSTRAINT OPERACAO_RENDA_FIXA_COMPROMISSADA_PK                                             PRIMARY KEY (ID) ENABLE
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA TO USER_GESTAO_RECURSOS_FINANCEIROS;

COMMENT ON TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA
    IS 'Tabela responsável por armazenar os dados das operações financeiras - Renda Fixa Compromissada.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA.ID
    IS 'Identificador único.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';

CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA_LASTRO
(
    ID                                  VARCHAR2(36)    NOT NULL,
    CADASTRO                            TIMESTAMP       NOT NULL,
    ATUALIZACAO                         TIMESTAMP       NOT NULL,
    OPERACAO_RENDA_FIXA_COMPROMISSADA   VARCHAR(36)     NOT NULL,
    CONSTRAINT OPERACAO_RENDA_FIXA_COMPROMISSADA_LASTRO_PK                                      PRIMARY KEY (ID) ENABLE,
    CONSTRAINT OPERACAO_RENDA_FIXA_COMPROMISSADA_LASTRO_FK_OPERACAO_RENDA_FIXA_COMPROMISSADA    FOREIGN KEY (OPERACAO_RENDA_FIXA_COMPROMISSADA)
        REFERENCES GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA (ID)

) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA_LASTRO TO USER_GESTAO_RECURSOS_FINANCEIROS;

COMMENT ON TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA_LASTRO
    IS 'Tabela responsável por armazenar os dados dos lastros das operações financeiras - Renda Fixa Compromissada.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA_LASTRO.ID
    IS 'Identificador único.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA_LASTRO.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA_LASTRO.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
COMMENT ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_COMPROMISSADA_LASTRO.OPERACAO_RENDA_FIXA_COMPROMISSADA
    IS 'Relacionamento tabela OPERACAO_RENDA_FIXA_COMPROMISSADA.';
