CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO
(
    ID                      VARCHAR2(36)    NOT NULL,
    CADASTRO                TIMESTAMP       NOT NULL,
    ATUALIZACAO             TIMESTAMP       NOT NULL,
    INDICADOR_FINANCEIRO    VARCHAR2(36)    NOT NULL,
    SISTEMA                 VARCHAR2(64)    NOT NULL,
    CODIGO                  VARCHAR2(16)    NOT NULL,
    SITUACAO                VARCHAR2(36)    NOT NULL,
    CONSTRAINT INDICADOR_FINANCEIRO_SINCRONIZACAO_PK                       PRIMARY KEY (ID) ENABLE,
    CONSTRAINT INDICADOR_FINANCEIRO_SINCRONIZACAO_FK_INDICADOR_FINANCEIRO  FOREIGN KEY (INDICADOR_FINANCEIRO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO (ID),
    CONSTRAINT INDICADOR_FINANCEIRO_SINCRONIZACAO_UNIQUE                   UNIQUE (INDICADOR_FINANCEIRO, SISTEMA, CODIGO)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
COMMENT
    ON TABLE GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO
    IS 'Configuração da sincronização da indicador.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO.ID
    IS 'Identificador único.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO.INDICADOR_FINANCEIRO
    IS 'Vinculo com o indicador financeiro. INDICADOR_FINANCEIRO.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO.SISTEMA
    IS 'Fluxo / Sistema externo para sincronizar a carga.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO.CODIGO
    IS 'Código de sincronização.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO.SITUACAO
    IS 'Situação da configuração da sincronização.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_SINCRONIZACAO TO USER_GESTAO_RECURSOS_FINANCEIROS;
