 
CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO
(
    ID                                  VARCHAR2(36)        NOT NULL,
    CADASTRO                            TIMESTAMP           NOT NULL,
    ATUALIZACAO                         TIMESTAMP           NOT NULL,
    INSTRUMENTO_FINANCEIRO_GIF_CODIGO   NUMBER              NOT NULL,
    CONSTRAINT INSTRUMENTO_FINANCEIRO_PK                    PRIMARY KEY (ID) ENABLE,
    CONSTRAINT UNIQUE_INSTRUMENTO_FINANCEIRO_GIF_CODIGO UNIQUE (INSTRUMENTO_FINANCEIRO_GIF_CODIGO)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;

COMMENT
ON TABLE GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO
    IS 'Tabela responsável por armazenar os dados dos Instrumentos Financeiros.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO.ID
    IS 'Identificador único.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTRUMENTO_FINANCEIRO.INSTRUMENTO_FINANCEIRO_GIF_CODIGO
    IS 'Vinculo com o registro do instrumento financeiro no GIF.';
