
-- alterando VALOR_FINANCEIRO
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_PRIMARIO ADD VALOR_FINANCEIRO DECIMAL(10,2) NULL;

UPDATE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_PRIMARIO A SET A.VALOR_FINANCEIRO = (SELECT B.VALOR_FINANCEIRO FROM GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA B WHERE B.ID = A.ID);

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_PRIMARIO MODIFY ( VALOR_FINANCEIRO NOT NULL);

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA DROP COLUMN VALOR_FINANCEIRO;

-- alterando QTD_DIAS para QUANTIDADE
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA RENAME COLUMN QTD_DIAS TO QUANTIDADE;

COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA.QUANTIDADE
    IS 'Quantidade de cotas';

-- alterando campos dependentes do CUPOM
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA MODIFY ( PERIODO_CUPOM NULL);

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA MODIFY ( DATA_PRIMEIRO_CUPOM NULL);

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA ADD CONSTRAINT CHECK_PERIODO_CUPOM
    CHECK (CUPOM = 0 OR (CUPOM = 1 AND PERIODO_CUPOM IS NOT NULL));
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA ADD CONSTRAINT CHECK_DATA_PRIMEIRO_CUPOM
    CHECK (CUPOM = 0 OR (CUPOM = 1 AND DATA_PRIMEIRO_CUPOM IS NOT NULL));

-- alterando a CODIGO_CUSTODIA_BB
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA MODIFY ( CODIGO_CUSTODIA_BB NULL);

-- adicionando/corrigindo comentarios
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_PRIMARIO.VALOR_FINANCEIRO
    IS 'Valor financeiro';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO.TIPO_TAXA_NEGOCIACAO
    IS 'Tipo de taxa na negociação PRE, POS, PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO.TAXA_EFETIVA_NEGOCIACAO
    IS 'Valor em percentual da taxa efetiva de negociação, valido para TIPO_TAXA_NEGOCIACAO igual a PRE';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO.TAXA_PRE_NEGOCIACAO
    IS 'Valor em percentual da taxa pre de negociacao, valido para TIPO_TAXA_NEGOCIACAO igual a PRE ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO.DIAS_UTEIS_NEGOCIACAO
    IS 'Dias uteis de negociaçao, valido para TIPO_TAXA_NEGOCIACAO igual a PRE ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO.INDICE_NEGOCIACAO
    IS 'Indice de negociacao (Indicador Financeiro) valido para TIPO_TAXA_NEGOCIACAO igual a POS ou PRE-POS';
COMMENT
ON COLUMN GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO.PERCENTUAL_NEGOCIACAO
    IS 'Valor em percentual do campo indice de negociacao, valido para TIPO_TAXA_NEGOCIACAO igual a POS ou PRE-POS';
