
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA RENAME COLUMN DATA_LIQUIDACAO TO DATA_LIQUIDEZ;

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO ADD TIPO_TAXA_NEGOCIACAO VARCHAR(10) NULL;
UPDATE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO SET TIPO_TAXA_NEGOCIACAO = TIPO_TAXA;
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO MODIFY ( TIPO_TAXA_NEGOCIACAO NOT NULL);

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO ADD TAXA_EFETIVA_NEGOCIACAO DECIMAL(10,2) NULL;
UPDATE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO SET TAXA_EFETIVA_NEGOCIACAO = 0 WHERE TIPO_TAXA IN('PRE','PRE_POS');

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP CONSTRAINT CHECK_INDICE_NEGOCIACAO;
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP CONSTRAINT CHECK_PERCENTUAL_NEGOCIACAO;
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP CONSTRAINT CHECK_TAXA_PRE_NEGOCIACAO;
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO DROP CONSTRAINT CHECK_DIAS_UTEIS_NEGOCIACAO;


ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO ADD CONSTRAINT CHECK_INDICE_NEGOCIACAO
    CHECK (TIPO_TAXA_NEGOCIACAO = 'PRE' OR (TIPO_TAXA_NEGOCIACAO IN('POS','PRE_POS') AND INDICE_NEGOCIACAO IS NOT NULL));
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO ADD CONSTRAINT CHECK_PERCENTUAL_NEGOCIACAO
    CHECK (TIPO_TAXA_NEGOCIACAO = 'PRE' OR (TIPO_TAXA_NEGOCIACAO IN('POS','PRE_POS') AND PERCENTUAL_NEGOCIACAO IS NOT NULL));

ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO ADD CONSTRAINT CHECK_TAXA_PRE_NEGOCIACAO
    CHECK (TIPO_TAXA_NEGOCIACAO = 'POS' OR (TIPO_TAXA_NEGOCIACAO IN('PRE','PRE_POS') AND TAXA_PRE_NEGOCIACAO IS NOT NULL));
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO ADD CONSTRAINT CHECK_DIAS_UTEIS_NEGOCIACAO
    CHECK (TIPO_TAXA_NEGOCIACAO = 'POS' OR (TIPO_TAXA_NEGOCIACAO IN('PRE','PRE_POS') AND ( DIAS_UTEIS_NEGOCIACAO IS NOT NULL AND (DIAS_UTEIS_NEGOCIACAO = 0 OR DIAS_UTEIS_NEGOCIACAO = 1 ))));
ALTER TABLE GESTAO_RECURSOS_FINANCEIROS.OPERACAO_RENDA_FIXA_DEFINITIVA_SECUNDARIO ADD CONSTRAINT CHECK_TAXA_EFETIVA_NEGOCIACAO
    CHECK (TIPO_TAXA_NEGOCIACAO = 'POS' OR (TIPO_TAXA_NEGOCIACAO IN('PRE','PRE_POS') AND TAXA_EFETIVA_NEGOCIACAO IS NOT NULL));


