CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA
(
    ID                      VARCHAR2(36)    NOT NULL,
    CADASTRO                TIMESTAMP       NOT NULL,
    ATUALIZACAO             TIMESTAMP       NOT NULL,
    INDICADOR_FINANCEIRO    VARCHAR2(36)    NOT NULL,
    REFERENCIA              DATE            NOT NULL,
    VALOR                   NUMBER(19,8)    NOT NULL,
    DIARIO                  NUMBER(19,8)    NOT NULL,
    CONSTRAINT INDICADOR_FINANCEIRO_TAXA_PK                         PRIMARY KEY (ID) ENABLE,
    CONSTRAINT INDICADOR_FINANCEIRO_TAXA_FK_INDICADOR_FINANCEIRO    FOREIGN KEY (INDICADOR_FINANCEIRO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO (ID),
    CONSTRAINT INDICADOR_FINANCEIRO_TAXA_UNIQUE                     UNIQUE (INDICADOR_FINANCEIRO, REFERENCIA)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
COMMENT
    ON TABLE GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA
    IS 'Indicadores financeiros.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA.ID
    IS 'Identificador único.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA.INDICADOR_FINANCEIRO
    IS 'Vinculo com o indicador financeiro. INDICADOR_FINANCEIRO.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA.REFERENCIA
    IS 'Data/dia de referência da Taxa do Indicador Financeiro.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA.VALOR
    IS 'Valor da Taxa do do Indicador Financeiro.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA.DIARIO
    IS 'Calulo diário base 252 para indicadores de períodicidade ANUAL.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO_TAXA TO USER_GESTAO_RECURSOS_FINANCEIROS;
