CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO
(
    ID                      VARCHAR2(36)    NOT NULL,
    CADASTRO                TIMESTAMP       NOT NULL,
    ATUALIZACAO             TIMESTAMP       NOT NULL,
    INSTITUICAO_FINANCEIRA  VARCHAR2(36)    NOT NULL,
    CLASSIFICACAO           VARCHAR2(36)    ,
    MOODYS                  VARCHAR2(36)    ,
    S_P                     VARCHAR2(36)    ,
    FITCH                   VARCHAR2(36)    ,
    RISK_BANK               VARCHAR2(36)    ,
    POUPEX                  VARCHAR2(36)    ,
    CONSTRAINT INSTITUICAO_FINANCEIRA_RISCO_PK                        PRIMARY KEY (ID) ENABLE,
    CONSTRAINT INSTITUICAO_FINANCEIRA_RISCO_FK_INSTITUICAO_FINANCEIRA FOREIGN KEY (INSTITUICAO_FINANCEIRA) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA (ID)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
COMMENT
    ON TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO
    IS 'Dados do risco da INSTITUICAO_FINANCEIRA_RISCO.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.ID
    IS 'Identificador único.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.INSTITUICAO_FINANCEIRA
    IS 'Vinculo da instituição financeira (INSTITUICAO_FINANCEIRA).';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.CLASSIFICACAO
    IS 'Classificação do risco.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.MOODYS
    IS 'Avaliação MOODYS.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.S_P
    IS 'Avaliação S&P.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.FITCH
    IS 'Avaliação FITCH.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.RISK_BANK
    IS 'Avaliação RISK_BANK.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.POUPEX
    IS 'Avaliação POUPEX.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA_RISCO TO USER_GESTAO_RECURSOS_FINANCEIROS;
