CREATE TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA
(
    ID                                      VARCHAR2(36)        NOT NULL,
    CADASTRO                                TIMESTAMP           NOT NULL,
    ATUALIZACAO                             TIMESTAMP           NOT NULL,
    CNPJ                                    VARCHAR2(14)        NOT NULL,
    NOME                                    VARCHAR2(256)       NOT NULL,
    ABREVIACAO                              VARCHAR2(256)       NOT NULL,
    MATRIZ                                  NUMBER(1)           NOT NULL,
    GRUPO                                   VARCHAR2(36)        ,
    TIPO                                    VARCHAR2(64)        NOT NULL,
    SITE                                    VARCHAR2(1000)      ,
    CETIP                                   VARCHAR2(512)       ,
    SELIQ                                   VARCHAR2(512)       ,
    CONSTRAINT INSTITUICAO_FINANCEIRA_PK                                    PRIMARY KEY (ID) ENABLE,
    CONSTRAINT INSTITUICAO_FINANCEIRA_FK_INSTITUICAO_FINANCEIRA_GRUPO       FOREIGN KEY (GRUPO) REFERENCES GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA (ID)
) TABLESPACE GESTAO_RECURSOS_FINAN_DATA;
COMMENT
    ON TABLE GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA
    IS 'Dados básicos das Instituições financeiras.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.ID
    IS 'Identificador único.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.CNPJ
    IS 'Número do CNPJ da instituição.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.NOME
    IS 'Nome completo (razão social ou nome fantasia) da instiuição.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.ABREVIACAO
    IS 'Abreviação da Instituição (Para combos ou resumos).';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.MATRIZ
    IS 'Marcação se a Instituição é Matriz ou não (Para uso em GRUPO).';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.GRUPO
    IS 'Grupo associado para a Instuição, somente para MATRIZ == false.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.TIPO
    IS 'Tipo da Instituição.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.SITE
    IS 'URL do site ou endereço eletronico da Instituição.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.CETIP
    IS 'Código CETIP da Instituição.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.SELIQ
    IS 'Código CELIQ da Instituição.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.CADASTRO
    IS 'Data/Hora do cadastro do dado.';
COMMENT
    ON COLUMN GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA.ATUALIZACAO
    IS 'Data/Hora da última atualização do dado.';
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTAO_RECURSOS_FINANCEIROS.INSTITUICAO_FINANCEIRA TO USER_GESTAO_RECURSOS_FINANCEIROS;
