INSERT INTO GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO(ID, CADASTRO, ATUALIZACAO, SIGLA, NOME, PERIODICIDADE)
    VALUES ('b87f1e72-4683-42d4-8373-696bada72727', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'CDI', 'Taxa de juros - CDI anualizada base 252', 'DIARIO');
INSERT INTO GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO(ID, CADASTRO, ATUALIZACAO, SIGLA, NOME, PERIODICIDADE)
    VALUES ('677b8631-ec89-4cb4-b103-0b86947ba7ff', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SELIC', 'Taxa de juros - Selic anualizada base 252', 'DIARIO');
INSERT INTO GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO(ID, CADASTRO, ATUALIZACAO, SIGLA, NOME, PERIODICIDADE)
    VALUES ('89610eb6-b274-4e61-a914-c8e037206102', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'TR', 'Taxa referencial (TR)', 'DIARIO');
INSERT INTO GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO(ID, CADASTRO, ATUALIZACAO, SIGLA, NOME, PERIODICIDADE)
    VALUES ('656c9463-2232-415b-b889-aac5d4f93f04', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'IPCA', 'Índice nacional de preços ao consumidor-amplo (IPCA)', 'MENSAL');
INSERT INTO GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO(ID, CADASTRO, ATUALIZACAO, SIGLA, NOME, PERIODICIDADE)
    VALUES ('ccfd7a28-4892-4f17-aad6-022d0cd5c1e9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'IGP-M', 'Índice geral de preços do mercado (IGP-M)', 'MENSAL');
INSERT INTO GESTAO_RECURSOS_FINANCEIROS.INDICADOR_FINANCEIRO(ID, CADASTRO, ATUALIZACAO, SIGLA, NOME, PERIODICIDADE)
    VALUES ('a533c7a1-5877-4e63-acc2-015f5e954858', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'INCC', 'Índice nacional de custo da construção (INCC)', 'MENSAL');
